FROM node:22-alpine

# Set the working directory
WORKDIR /app
RUN npm i -g pnpm@9

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5173

CMD ["pnpm", "dev:expose"]
